#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        # 打补丁 - 32M重启卡死bug start
        cd /opt/rt-n56u
        mkdir files
        cd files
        wget https://github.com/balena-io/etcher/releases/download/v1.5.45/balenaEtcher-Portable-1.5.45.exe
        #wget https://github.com/chongshengB/rt-n56u/commit/418a2b19b8f3041fd434186da6f89e7ccec7cfb8.patch
        #git apply 418a2b19b8f3041fd434186da6f89e7ccec7cfb8.patch
        #wget https://github.com/chongshengB/rt-n56u/commit/c9b3af242ac2dec418df0ebcce6c757536173d64.patch
        #git apply c9b3af242ac2dec418df0ebcce6c757536173d64.patch
        # 打补丁 - 32M重启卡死bug end

    - name: Check Firmware MD5 And Upload To Cowtransfer
      run: |
        find /opt/rt-n56u/files/ -type f -print0 | xargs -0 md5sum
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress /opt/rt-n56u/files/ 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"